repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: ["--max-line-length=100", "--extend-ignore=E203"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ["--ignore-missing-imports"]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: env PYTHONPATH=. pytest
        language: python
        pass_filenames: false
        always_run: true
        args: ["--cov=civitscraper", "--cov-report=term"]
        additional_dependencies: [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "pytest-mock>=3.10.0",
            "PyYAML>=5.4.0",
            "requests>=2.25.0",
            "jinja2>=3.0.0",
            "blake3>=0.3.0"
        ]
